DSBDA 1 PRACTICAL

Perform the following operations using Python on any open source dataset (e.g., data.csv) the data types (i.e., character, numeric,
integer, factor, and logical) of the variables in the
1. Import all the required Python Libraries.
2. Locate an open source data from the web (e.g., https://www.kaggle.com). Provide a clear description of the data and its source (i.e., URL
of the web site).
3. Load the Dataset into pandas dataframe.
4. Data Preprocessing: check for missing values in the data using pandas isnull(), describe() function to get some initial statistics.
Provide variable descriptions. Types of variables etc. Check the dimensions of the data frame.
5. Data Formatting and Data Normalization: Summarize the types of variables by checking
data set. If variables are not in the correct data type, apply proper type conversions. 6. Turn categorical variables into quantitative
variables in Python.

1) Import all the required Python Libraries.

In [17]:
import pandas as pd
import numpy as np

2) Locate an open source data from the web (e.g., https://www.kaggle.com). Provide a clear
description of the data and its source (i.e., URL of the web site).

3) Load the Dataset into pandas dataframe.

In [18]:
df=pd.read_csv('Weather Data.csv')

In [19]:
df

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [20]:
df.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [21]:
df.tail()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

4) Data Preprocessing: check for missing values in the data using pandas isnull(), describe()
function to get some initial statistics. Provide variable descriptions. Types of variables etc.
Check the dimensions of the data frame.

In [22]:
df.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [23]:
df.describe()

,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,8.798144,2.555294,67.431694,14.945469,27.664447,101.051623
std,11.687883,10.883072,16.918881,8.688696,12.622688,0.844005
min,-23.300000,-28.500000,18.000000,0.000000,0.200000,97.520000
25%,0.100000,-5.900000,56.000000,9.000000,24.100000,100.560000
50%,9.300000,3.300000,68.000000,13.000000,25.000000,101.070000
75%,18.800000,11.800000,81.000000,20.000000,25.000000,101.590000
max,33.000000,24.400000,100.000000,83.000000,48.300000,103.650000

In [24]:
df.shape

(8784, 8)

In [25]:
df.isna().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [26]:
df.sort_values(by="Temp_C")

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
344,1/15/2012 8:00,-23.3,-28.5,62,7,24.1,102.45,Clear
342,1/15/2012 6:00,-23.2,-28.5,62,7,25.0,102.28,Mostly Cloudy
343,1/15/2012 7:00,-22.8,-28.0,62,9,25.0,102.37,Mainly Clear
345,1/15/2012 9:00,-22.2,-27.8,60,9,48.3,102.57,Mainly Clear
338,1/15/2012 2:00,-21.4,-26.6,63,9,25.0,101.99,Cloudy
...,...,...,...,...,...,...,...,...
4694,7/14/2012 14:00,32.7,15.3,35,28,48.3,101.35,Mainly Clear
5199,8/4/2012 15:00,32.8,18.8,44,17,24.1,101.39,Clear
4696,7/14/2012 16:00,32.9,15.3,35,24,48.3,101.26,Mainly Clear
4143,6/21/2012 15:00,33.0,19.0,44,24,24.1,100.20,Mainly Clear
4695,7/14/2012 15:00,33.0,16.8,38,22,48.3,101.31,Mainly Clear

In [28]:
df.isna().sum(axis=1)

0       0
1       0
2       0
3       0
4       0
       ..
8779    0
8780    0
8781    0
8782    0
8783    0
Length: 8784, dtype: int64

In [30]:
df["Wind Speed_km/h"].value_counts()

Wind Speed_km/h
9     830
11    791
13    735
15    719
7     677
17    666
19    616
6     609
20    496
4     474
22    439
24    374
0     309
26    242
28    205
30    161
32    139
33     85
35     53
37     45
39     24
41     22
44     14
43     13
48     13
46     11
52      7
57      5
50      4
2       2
83      1
70      1
63      1
54      1
Name: count, dtype: int64

In [31]:
df.dtypes

Date/Time            object
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather              object
dtype: object

In [32]:
df=pd.get_dummies(df,columns=["Rel Hum_%"])

In [33]:
df

,Date/Time,Temp_C,Dew Point Temp_C,Wind Speed_km/h,Visibility_km,Press_kPa,Weather,Rel Hum_%_18,Rel Hum_%_19,Rel Hum_%_20,...,Rel Hum_%_91,Rel Hum_%_92,Rel Hum_%_93,Rel Hum_%_94,Rel Hum_%_95,Rel Hum_%_96,Rel Hum_%_97,Rel Hum_%_98,Rel Hum_%_99,Rel Hum_%_100
0,1/1/2012 0:00,-1.8,-3.9,4,8.0,101.24,Fog,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1/1/2012 1:00,-1.8,-3.7,4,8.0,101.24,Fog,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,1/1/2012 2:00,-1.8,-3.4,7,4.0,101.26,"Freezing Drizzle,Fog",False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,1/1/2012 3:00,-1.5,-3.2,6,4.0,101.27,"Freezing Drizzle,Fog",False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,1/1/2012 4:00,-1.5,-3.3,7,4.8,101.23,Fog,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,30,9.7,100.13,Snow,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8780,12/31/2012 20:00,0.2,-2.4,24,9.7,100.03,Snow,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8781,12/31/2012 21:00,-0.5,-1.5,28,4.8,99.95,Snow,False,False,False,...,False,False,True,False,False,False,False,False,False,False
8782,12/31/2012 22:00,-0.2,-1.8,28,9.7,99.91,Snow,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8783,12/31/2012 23:00,0.0,-2.1,30,11.3,99.89,Snow,False,False,False,...,False,False,False,False,False,False,False,False,False,False

5) Data Formatting and Data Normalization: Summarize the types of variables by checking the
data types (i.e., character, numeric, integer, factor, and logical)of the variables in the data set. If
variables are not in the correct data type, apply proper type conversions.

In [34]:
df['Temp_C']=df['Temp_C'].astype('int64')

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 90 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   int64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Wind Speed_km/h   8784 non-null   int64
 4   Visibility_km     8784 non-null   float64
 5   Press_kPa         8784 non-null   float64
 6   Weather           8784 non-null   object
 7   Rel Hum_%_18      8784 non-null   bool
 8   Rel Hum_%_19      8784 non-null   bool
 9   Rel Hum_%_20      8784 non-null   bool
 10  Rel Hum_%_21      8784 non-null   bool
 11  Rel Hum_%_22      8784 non-null   bool
 12  Rel Hum_%_23      8784 non-null   bool
 13  Rel Hum_%_24      8784 non-null   bool
 14  Rel Hum_%_25      8784 non-null   bool
 15  Rel Hum_%_26      8784 non-null   bool
 16  Rel Hum_%_27      8784 non-null   bool
 17  Rel Hum_%_28      8784 non-null   bool
 18  Rel Hum_%_29      8784 non-null   bool
 19  Rel Hum_%_30      8784 non-null   bool
 20  Rel Hum_%_31      8784 non-null   bool
 21  Rel Hum_%_32      8784 non-null   bool
 22  Rel Hum_%_33      8784 non-null   bool
 23  Rel Hum_%_34      8784 non-null   bool
 24  Rel Hum_%_35      8784 non-null   bool
 25  Rel Hum_%_36      8784 non-null   bool
 26  Rel Hum_%_37      8784 non-null   bool
 27  Rel Hum_%_38      8784 non-null   bool
 28  Rel Hum_%_39      8784 non-null   bool
 29  Rel Hum_%_40      8784 non-null   bool
 30  Rel Hum_%_41      8784 non-null   bool
 31  Rel Hum_%_42      8784 non-null   bool
 32  Rel Hum_%_43      8784 non-null   bool
 33  Rel Hum_%_44      8784 non-null   bool
 34  Rel Hum_%_45      8784 non-null   bool
 35  Rel Hum_%_46      8784 non-null   bool
 36  Rel Hum_%_47      8784 non-null   bool
 37  Rel Hum_%_48      8784 non-null   bool
 38  Rel Hum_%_49      8784 non-null   bool
 39  Rel Hum_%_50      8784 non-null   bool
 40  Rel Hum_%_51      8784 non-null   bool
 41  Rel Hum_%_52      8784 non-null   bool
 42  Rel Hum_%_53      8784 non-null   bool
 43  Rel Hum_%_54      8784 non-null   bool
 44  Rel Hum_%_55      8784 non-null   bool
 45  Rel Hum_%_56      8784 non-null   bool
 46  Rel Hum_%_57      8784 non-null   bool
 47  Rel Hum_%_58      8784 non-null   bool
 48  Rel Hum_%_59      8784 non-null   bool
 49  Rel Hum_%_60      8784 non-null   bool
 50  Rel Hum_%_61      8784 non-null   bool
 51  Rel Hum_%_62      8784 non-null   bool
 52  Rel Hum_%_63      8784 non-null   bool
 53  Rel Hum_%_64      8784 non-null   bool
 54  Rel Hum_%_65      8784 non-null   bool
 55  Rel Hum_%_66      8784 non-null   bool
 56  Rel Hum_%_67      8784 non-null   bool
 57  Rel Hum_%_68      8784 non-null   bool
 58  Rel Hum_%_69      8784 non-null   bool
 59  Rel Hum_%_70      8784 non-null   bool
 60  Rel Hum_%_71      8784 non-null   bool
 61  Rel Hum_%_72      8784 non-null   bool
 62  Rel Hum_%_73      8784 non-null   bool
 63  Rel Hum_%_74      8784 non-null   bool
 64  Rel Hum_%_75      8784 non-null   bool
 65  Rel Hum_%_76      8784 non-null   bool
 66  Rel Hum_%_77      8784 non-null   bool
 67  Rel Hum_%_78      8784 non-null   bool
 68  Rel Hum_%_79      8784 non-null   bool
 69  Rel Hum_%_80      8784 non-null   bool
 70  Rel Hum_%_81      8784 non-null   bool
 71  Rel Hum_%_82      8784 non-null   bool
 72  Rel Hum_%_83      8784 non-null   bool
 73  Rel Hum_%_84      8784 non-null   bool
 74  Rel Hum_%_85      8784 non-null   bool
 75  Rel Hum_%_86      8784 non-null   bool
 76  Rel Hum_%_87      8784 non-null   bool
 77  Rel Hum_%_88      8784 non-null   bool
 78  Rel Hum_%_89      8784 non-null   bool
 79  Rel Hum_%_90      8784 non-null   bool
 80  Rel Hum_%_91      8784 non-null   bool
 81  Rel Hum_%_92      8784 non-null   bool
 82  Rel Hum_%_93      8784 non-null   bool
 83  Rel Hum_%_94      8784 non-null   bool
 84  Rel Hum_%_95      8784 non-null   bool
 85  Rel Hum_%_96      8784 non-null   bool
 86  Rel Hum_%_97      8784 non-null   bool
 87  Rel Hum_%_98      8784 non-null   bool
 88  Rel Hum_%_99      8784 non-null   bool
 89  Rel Hum_%_100     8784 non-null   bool
dtypes: bool(83), float64(3), int64(2), object(2)
memory usage: 1.2+ MB